export const FETCH_BUCKETLIST = 'FETCH_BUCKETLIST';
export const FETCH_BUCKETLIST_SUCCEEDED = 'FETCH_BUCKETLIST_SUCCEEDED';
export const FETCH_BUCKETLIST_FAILED = 'FETCH_BUCKETLIST_FAILED';
export const ADD_NEW_PLACE = 'ADD_NEW_PLACE';
export const ADD_NEW_PLACE_SUCCEEDED = 'ADD_NEW_PLACE_SUCCEEDED';
export const ADD_NEW_PLACE_FAILED = 'ADD_NEW_PLACE_FAILED';
export const LOGGED_IN = 'LOGGED_IN';
